### ISSUE TITLE
Zip/Unzip no longer works

### ISSUE THREAD

**Issue by benspargo89** [ManivannanMurugavel/selenium-python-aws-lambda#4]
I downloaded the ZIP, uploaded to AWS, and the lambda ran successfully. If I simply download the zip > extract all > send to compressed file, it no longer works when I upload it. I tracked back to this after trying upload edited code and having it fail. 

Is there some step/procedure that I am missing? Some other way of extracting/zipping? I tried through direct upload and S3.

After unzipping and rezipping I get the unable to import lambda_function error (when this python file is still in the folder and unchanged)

{
  "errorMessage": "Unable to import module 'lambda_function'"
}

Thanks for any help!

**Comment by cptrfan** [comment]
I just encountered the exact same issue and was able to resolve it.
In case anyone is experiencing the same issue, I will leave a note here on how I resolved it.

Basically, the issue was when I zipped the files, I was selecting the root folder and zip it.
However, this will create another folder layer in the zip file.
You can verify this by unzipping the zip file you've just created, and compare with the original unzipped folder; you will see extra folder layer there before getting to the script files like easy_install.py or lambda_function.py.

So the solution was, instead of selecting one folder and zip it, go into the folder and select all the folders and .py files and zip them.
I also found that Windows default zip application does not always maintain the Linux file attributes,
so zipping the files on Ubuntu worked for me.

On Ubuntu,
```bash
# Install zip and unzip
sudo apt-get install zip unzip

# Download lambda_function.zip from this repository
wget https://github.com/ManivannanMurugavel/selenium-python-aws-lambda/raw/master/lambda_function.zip

# Create a folder to store the content of lambda_function.zip
mkdir lambda_function

# Unzip lambda_function.zip into the folder you just created
unzip lambda_function.zip -d lambda_function/

# Go into the folder
cd lambda_function

# Now, modify lambda_function.py however you want.

# Create a new zip file with your changes
zip -r {your_desired_destination_folder}/lambda_function.zip *
```
Then, upload the newly created lambda_function.zip to your AWS S3.
Hope this helps!

**Comment by ManivannanMurugavel** [comment]
Hi,
Thanks for your explanation...
